-- PUBLIC.ACCOUNT definition

-- Drop table

-- DROP TABLE PUBLIC.ACCOUNT;

CREATE TABLE PUBLIC.ACCOUNT (
                                "UUID" UUID NOT NULL,
                                PASSWORD CHARACTER VARYING(255) NOT NULL,
                                STATUS CHARACTER VARYING(255) NOT NULL,
                                USER_ID CHARACTER VARYING(255) NOT NULL,
                                CONSTRAINT CONSTRAINT_E PRIMARY KEY ("UUID")
);
CREATE UNIQUE INDEX PRIMARY_KEY_E ON PUBLIC.ACCOUNT ("UUID");


-- PUBLIC.CITY definition

-- Drop table

-- DROP TABLE PUBLIC.CITY;

CREATE TABLE PUBLIC.CITY (
                             "UUID" UUID NOT NULL,
                             CITY CHARACTER VARYING(255) NOT NULL,
                             COUNTRY CHARACTER VARYING(255) NOT NULL,
                             STATE CHARACTER VARYING(255) NOT NULL,
                             ZIP_CODE CHARACTER VARYING(255) NOT NULL,
                             CONSTRAINT CONSTRAINT_1 PRIMARY KEY ("UUID")
);
CREATE UNIQUE INDEX PRIMARY_KEY_1 ON PUBLIC.CITY ("UUID");
CREATE UNIQUE INDEX UK9S1N56J4O997FPCP1DO8JUEL1_INDEX_1 ON PUBLIC.CITY (CITY);
CREATE UNIQUE INDEX UK_FYWT1LWMD5R4O5M3GQKT1I1BD_INDEX_1 ON PUBLIC.CITY (ZIP_CODE);


-- PUBLIC.MOVIE definition

-- Drop table

-- DROP TABLE PUBLIC.MOVIE;

CREATE TABLE PUBLIC.MOVIE (
                              "UUID" UUID NOT NULL,
                              DESCRIPTION CHARACTER VARYING(255) NOT NULL,
                              DURATION_IN_MINS INTEGER NOT NULL,
                              GENRE CHARACTER VARYING(255) NOT NULL,
                              "LANGUAGE" CHARACTER VARYING(255) NOT NULL,
                              RELEASE_DATE TIMESTAMP NOT NULL,
                              TITLE CHARACTER VARYING(255) NOT NULL,
                              CONSTRAINT CONSTRAINT_4 PRIMARY KEY ("UUID")
);
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PUBLIC.MOVIE ("UUID");


-- PUBLIC.PAYMENT definition

-- Drop table

-- DROP TABLE PUBLIC.PAYMENT;

CREATE TABLE PUBLIC.PAYMENT (
                                "UUID" UUID NOT NULL,
                                AMOUNT DOUBLE PRECISION NOT NULL,
                                STATUS CHARACTER VARYING(255) NOT NULL,
                                TRANSACTION_ID UUID NOT NULL,
                                CONSTRAINT CONSTRAINT_F PRIMARY KEY ("UUID")
);
CREATE UNIQUE INDEX PRIMARY_KEY_F ON PUBLIC.PAYMENT ("UUID");


-- PUBLIC.ADDRESS definition

-- Drop table

-- DROP TABLE PUBLIC.ADDRESS;

CREATE TABLE PUBLIC.ADDRESS (
                                "UUID" UUID NOT NULL,
                                ADDRESS_LINE1 CHARACTER VARYING(255) NOT NULL,
                                ADDRESS_LINE2 CHARACTER VARYING(255),
                                ADDRESS_LINE3 CHARACTER VARYING(255),
                                CITY_UUID UUID NOT NULL,
                                CONSTRAINT CONSTRAINT_E6 PRIMARY KEY ("UUID"),
                                CONSTRAINT FK5JMJXB57QB2RRUV9O2UIDIFY5 FOREIGN KEY (CITY_UUID) REFERENCES PUBLIC.CITY("UUID") ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX IDX90A4TXMNFYDOIBD2KK973YJQB ON PUBLIC.ADDRESS (CITY_UUID);
CREATE UNIQUE INDEX PRIMARY_KEY_E6 ON PUBLIC.ADDRESS ("UUID");


-- PUBLIC.PLATFORM_USER definition

-- Drop table

-- DROP TABLE PUBLIC.PLATFORM_USER;

CREATE TABLE PUBLIC.PLATFORM_USER (
                                      "UUID" UUID NOT NULL,
                                      EMAIL CHARACTER VARYING(255) NOT NULL,
                                      FIRST_NAME CHARACTER VARYING(255) NOT NULL,
                                      LAST_NAME CHARACTER VARYING(255) NOT NULL,
                                      PHONE_NO CHARACTER VARYING(255) NOT NULL,
                                      "TYPE" CHARACTER VARYING(255) NOT NULL,
                                      ACCOUNT_UUID UUID,
                                      ADDRESS_UUID UUID,
                                      CONSTRAINT CONSTRAINT_D PRIMARY KEY ("UUID"),
                                      CONSTRAINT FK3B9WNIJ4M9N2YJAF977YN0J9V FOREIGN KEY (ADDRESS_UUID) REFERENCES PUBLIC.ADDRESS("UUID") ON DELETE RESTRICT ON UPDATE RESTRICT,
                                      CONSTRAINT FKKFO7PJ6UPTP8E6F35H1E41TPW FOREIGN KEY (ACCOUNT_UUID) REFERENCES PUBLIC.ACCOUNT("UUID") ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FK3B9WNIJ4M9N2YJAF977YN0J9V_INDEX_D ON PUBLIC.PLATFORM_USER (ADDRESS_UUID);
CREATE INDEX FKKFO7PJ6UPTP8E6F35H1E41TPW_INDEX_D ON PUBLIC.PLATFORM_USER (ACCOUNT_UUID);
CREATE UNIQUE INDEX PRIMARY_KEY_D ON PUBLIC.PLATFORM_USER ("UUID");


-- PUBLIC.THEATRE definition

-- Drop table

-- DROP TABLE PUBLIC.THEATRE;

CREATE TABLE PUBLIC.THEATRE (
                                "UUID" UUID NOT NULL,
                                NAME CHARACTER VARYING(255) NOT NULL,
                                ADDRESS_UUID UUID,
                                CONSTRAINT CONSTRAINT_DA PRIMARY KEY ("UUID"),
                                CONSTRAINT FKIUB2YTM2BF4DFSN53OQE708SY FOREIGN KEY (ADDRESS_UUID) REFERENCES PUBLIC.ADDRESS("UUID") ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE UNIQUE INDEX PRIMARY_KEY_DA ON PUBLIC.THEATRE ("UUID");
CREATE UNIQUE INDEX UKQESJT5SUXESNYMKMJK8N3KFPF_INDEX_D ON PUBLIC.THEATRE (ADDRESS_UUID);


-- PUBLIC.BOOKING definition

-- Drop table

-- DROP TABLE PUBLIC.BOOKING;

CREATE TABLE PUBLIC.BOOKING (
                                "UUID" UUID NOT NULL,
                                BOOKED_ON TIMESTAMP NOT NULL,
                                NUMBER_OF_SEATS INTEGER NOT NULL,
                                STATUS CHARACTER VARYING(255) NOT NULL,
                                PAYMENT_UUID UUID,
                                USER_UUID UUID NOT NULL,
                                CONSTRAINT CONSTRAINT_2 PRIMARY KEY ("UUID"),
                                CONSTRAINT FKFN3AXA7ST8FUHE77L1EVYDTXN FOREIGN KEY (USER_UUID) REFERENCES PUBLIC.PLATFORM_USER("UUID") ON DELETE RESTRICT ON UPDATE RESTRICT,
                                CONSTRAINT FKGM14IX6HW92JRUILVNO3TNGM6 FOREIGN KEY (PAYMENT_UUID) REFERENCES PUBLIC.PAYMENT("UUID") ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FKFN3AXA7ST8FUHE77L1EVYDTXN_INDEX_2 ON PUBLIC.BOOKING (USER_UUID);
CREATE INDEX IDXFP54AKH61461T01HLHC6XVVPY ON PUBLIC.BOOKING (PAYMENT_UUID);
CREATE UNIQUE INDEX PRIMARY_KEY_2 ON PUBLIC.BOOKING ("UUID");


-- PUBLIC.HALL definition

-- Drop table

-- DROP TABLE PUBLIC.HALL;

CREATE TABLE PUBLIC.HALL (
                             "UUID" UUID NOT NULL,
                             NAME CHARACTER VARYING(255) NOT NULL,
                             TOTAL_SEATS INTEGER NOT NULL,
                             THEATRE_UUID UUID,
                             CONSTRAINT CONSTRAINT_21 PRIMARY KEY ("UUID"),
                             CONSTRAINT FKLLEUS4TOQE792B5UODUCNKGJQ FOREIGN KEY (THEATRE_UUID) REFERENCES PUBLIC.THEATRE("UUID") ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX IDX11TMQONQW4DOF4ETU76TBW61M ON PUBLIC.HALL (THEATRE_UUID);
CREATE UNIQUE INDEX PRIMARY_KEY_21 ON PUBLIC.HALL ("UUID");


-- PUBLIC.SEAT definition

-- Drop table

-- DROP TABLE PUBLIC.SEAT;

CREATE TABLE PUBLIC.SEAT (
                             "UUID" UUID NOT NULL,
                             COLUMN_NO INTEGER NOT NULL,
                             ROW_NO INTEGER NOT NULL,
                             "TYPE" CHARACTER VARYING(255) NOT NULL,
                             HALL_UUID UUID,
                             CONSTRAINT CONSTRAINT_26 PRIMARY KEY ("UUID"),
                             CONSTRAINT FKET27X62XXGIWRLI6TKC4MTKQU FOREIGN KEY (HALL_UUID) REFERENCES PUBLIC.HALL("UUID") ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX IDXQRIX8KJBP23MMJE4O61MD2LEV ON PUBLIC.SEAT (HALL_UUID);
CREATE UNIQUE INDEX PRIMARY_KEY_26 ON PUBLIC.SEAT ("UUID");


-- PUBLIC.SHOW definition

-- Drop table

-- DROP TABLE PUBLIC.SHOW;

CREATE TABLE PUBLIC.SHOW (
                             "UUID" UUID NOT NULL,
                             END_TIME TIMESTAMP NOT NULL,
                             START_TIME TIMESTAMP NOT NULL,
                             HALL_UUID UUID,
                             MOVIE_UUID UUID,
                             CONSTRAINT CONSTRAINT_26D PRIMARY KEY ("UUID"),
                             CONSTRAINT FK4TXX1FL7T5NG1MGFRPY433TSM FOREIGN KEY (MOVIE_UUID) REFERENCES PUBLIC.MOVIE("UUID") ON DELETE RESTRICT ON UPDATE RESTRICT,
                             CONSTRAINT FKI3N7J6WYMLIMRSGIYN7IPI2CT FOREIGN KEY (HALL_UUID) REFERENCES PUBLIC.HALL("UUID") ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX IDX4O1AINGDKXY0OAEHNJUTVFJ5T ON PUBLIC.SHOW (HALL_UUID);
CREATE INDEX IDXIDKWM04A5UGUIOEWJDB9IDM1H ON PUBLIC.SHOW (MOVIE_UUID);
CREATE UNIQUE INDEX PRIMARY_KEY_26D ON PUBLIC.SHOW ("UUID");


-- PUBLIC.RESERVATION definition

-- Drop table

-- DROP TABLE PUBLIC.RESERVATION;

CREATE TABLE PUBLIC.RESERVATION (
                                    "UUID" UUID NOT NULL,
                                    EXPIRY_TIME TIMESTAMP NOT NULL,
                                    PRICE DOUBLE PRECISION NOT NULL,
                                    STATUS CHARACTER VARYING(255) NOT NULL,
                                    BOOKING_UUID UUID,
                                    SEAT_UUID UUID,
                                    SHOW_UUID UUID,
                                    CONSTRAINT CONSTRAINT_23 PRIMARY KEY ("UUID"),
                                    CONSTRAINT FK8AQ57YPVT28CO94CFRX7ENCXT FOREIGN KEY (SEAT_UUID) REFERENCES PUBLIC.SEAT("UUID") ON DELETE RESTRICT ON UPDATE RESTRICT,
                                    CONSTRAINT FKMKFE9595B17QHC3KQM3KJJQMO FOREIGN KEY (BOOKING_UUID) REFERENCES PUBLIC.BOOKING("UUID") ON DELETE RESTRICT ON UPDATE RESTRICT,
                                    CONSTRAINT FKMXBCML8S4MEVY8OWLMYRV3G9T FOREIGN KEY (SHOW_UUID) REFERENCES PUBLIC.SHOW("UUID") ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FK8AQ57YPVT28CO94CFRX7ENCXT_INDEX_2 ON PUBLIC.RESERVATION (SEAT_UUID);
CREATE INDEX FKMXBCML8S4MEVY8OWLMYRV3G9T_INDEX_2 ON PUBLIC.RESERVATION (SHOW_UUID);
CREATE INDEX IDXKKSB54JQMHFEAO1O7U8HCC6WP ON PUBLIC.RESERVATION (BOOKING_UUID);
CREATE UNIQUE INDEX PRIMARY_KEY_23 ON PUBLIC.RESERVATION ("UUID");
CREATE UNIQUE INDEX UKH70BFY5KM78MQ9IO3LICGTP98_INDEX_2 ON PUBLIC.RESERVATION (SHOW_UUID,SEAT_UUID);